// Code generated by protoc-gen-go. DO NOT EDIT.
// source: JobServerConsole.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PyRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountName          string   `protobuf:"bytes,2,opt,name=accountName,proto3" json:"accountName,omitempty"`
	Position             string   `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Order                string   `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	Trade                string   `protobuf:"bytes,5,opt,name=trade,proto3" json:"trade,omitempty"`
	ErrMsg               string   `protobuf:"bytes,6,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PyRequest) Reset()         { *m = PyRequest{} }
func (m *PyRequest) String() string { return proto.CompactTextString(m) }
func (*PyRequest) ProtoMessage()    {}
func (*PyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_404207518f149c87, []int{0}
}

func (m *PyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PyRequest.Unmarshal(m, b)
}
func (m *PyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PyRequest.Marshal(b, m, deterministic)
}
func (m *PyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PyRequest.Merge(m, src)
}
func (m *PyRequest) XXX_Size() int {
	return xxx_messageInfo_PyRequest.Size(m)
}
func (m *PyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PyRequest proto.InternalMessageInfo

func (m *PyRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *PyRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *PyRequest) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *PyRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *PyRequest) GetTrade() string {
	if m != nil {
		return m.Trade
	}
	return ""
}

func (m *PyRequest) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type JobServerConsoleResponse struct {
	Rsp                  string   `protobuf:"bytes,1,opt,name=rsp,proto3" json:"rsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobServerConsoleResponse) Reset()         { *m = JobServerConsoleResponse{} }
func (m *JobServerConsoleResponse) String() string { return proto.CompactTextString(m) }
func (*JobServerConsoleResponse) ProtoMessage()    {}
func (*JobServerConsoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_404207518f149c87, []int{1}
}

func (m *JobServerConsoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobServerConsoleResponse.Unmarshal(m, b)
}
func (m *JobServerConsoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobServerConsoleResponse.Marshal(b, m, deterministic)
}
func (m *JobServerConsoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobServerConsoleResponse.Merge(m, src)
}
func (m *JobServerConsoleResponse) XXX_Size() int {
	return xxx_messageInfo_JobServerConsoleResponse.Size(m)
}
func (m *JobServerConsoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobServerConsoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobServerConsoleResponse proto.InternalMessageInfo

func (m *JobServerConsoleResponse) GetRsp() string {
	if m != nil {
		return m.Rsp
	}
	return ""
}

func init() {
	proto.RegisterType((*PyRequest)(nil), "main.PyRequest")
	proto.RegisterType((*JobServerConsoleResponse)(nil), "main.JobServerConsoleResponse")
}

func init() { proto.RegisterFile("JobServerConsole.proto", fileDescriptor_404207518f149c87) }

var fileDescriptor_404207518f149c87 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x5d, 0xdb, 0x2e, 0xee, 0x78, 0xa8, 0x8c, 0x52, 0x42, 0x11, 0x29, 0x7b, 0xf2, 0x20,
	0x7b, 0xa8, 0x8f, 0xa0, 0x07, 0x2b, 0x58, 0xca, 0xea, 0xcd, 0x53, 0xda, 0x0c, 0xb2, 0x60, 0x33,
	0x71, 0x92, 0x0a, 0x7d, 0x26, 0x5f, 0x52, 0x36, 0x1b, 0xaa, 0x2c, 0xf4, 0x96, 0xef, 0xfb, 0x43,
	0x32, 0xf3, 0xc3, 0xe4, 0x99, 0xd7, 0xaf, 0x24, 0xdf, 0x24, 0x0f, 0x6c, 0x3d, 0x7f, 0x52, 0xe5,
	0x84, 0x03, 0xe3, 0x70, 0xab, 0x1b, 0x5b, 0xfe, 0x64, 0x50, 0xac, 0xf6, 0x35, 0x7d, 0xed, 0xc8,
	0x07, 0xbc, 0x86, 0x42, 0x6f, 0x36, 0xbc, 0xb3, 0x61, 0x61, 0x54, 0x36, 0xcb, 0x6e, 0x8b, 0xfa,
	0x4f, 0xe0, 0x0c, 0xce, 0x13, 0x2c, 0xf5, 0x96, 0xd4, 0x69, 0xcc, 0xff, 0x2b, 0x9c, 0xc2, 0x99,
	0x63, 0xdf, 0x84, 0x86, 0xad, 0x1a, 0xc4, 0xf8, 0xc0, 0x78, 0x05, 0x23, 0x16, 0x43, 0xa2, 0x86,
	0x31, 0xe8, 0xa0, 0xb5, 0x41, 0xb4, 0x21, 0x35, 0xea, 0x6c, 0x04, 0x9c, 0x40, 0x4e, 0x22, 0x2f,
	0xfe, 0x43, 0xe5, 0x51, 0x27, 0x2a, 0xef, 0x40, 0xf5, 0xb7, 0xa9, 0xc9, 0x3b, 0xb6, 0x9e, 0xf0,
	0x02, 0x06, 0xe2, 0x5d, 0x9a, 0xba, 0x3d, 0xce, 0xdf, 0x61, 0xbc, 0x78, 0xab, 0x1f, 0x97, 0x6c,
	0x28, 0x5d, 0xc6, 0x27, 0xb8, 0x5c, 0xed, 0xe7, 0xfd, 0x37, 0x70, 0x5c, 0xb5, 0x65, 0x54, 0x87,
	0x22, 0xa6, 0x37, 0x9d, 0x38, 0xf6, 0x59, 0x79, 0xb2, 0xce, 0x63, 0x8b, 0xf7, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x0b, 0x85, 0xdb, 0xb3, 0x5f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ITRDNodeConsoleClient is the client API for ITRDNodeConsole service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ITRDNodeConsoleClient interface {
	Py2JobServerConsole(ctx context.Context, in *PyRequest, opts ...grpc.CallOption) (*JobServerConsoleResponse, error)
}

type iTRDNodeConsoleClient struct {
	cc *grpc.ClientConn
}

func NewITRDNodeConsoleClient(cc *grpc.ClientConn) ITRDNodeConsoleClient {
	return &iTRDNodeConsoleClient{cc}
}

func (c *iTRDNodeConsoleClient) Py2JobServerConsole(ctx context.Context, in *PyRequest, opts ...grpc.CallOption) (*JobServerConsoleResponse, error) {
	out := new(JobServerConsoleResponse)
	err := c.cc.Invoke(ctx, "/main.ITRDNodeConsole/Py2JobServerConsole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ITRDNodeConsoleServer is the server API for ITRDNodeConsole service.
type ITRDNodeConsoleServer interface {
	Py2JobServerConsole(context.Context, *PyRequest) (*JobServerConsoleResponse, error)
}

// UnimplementedITRDNodeConsoleServer can be embedded to have forward compatible implementations.
type UnimplementedITRDNodeConsoleServer struct {
}

func (*UnimplementedITRDNodeConsoleServer) Py2JobServerConsole(ctx context.Context, req *PyRequest) (*JobServerConsoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Py2JobServerConsole not implemented")
}

func RegisterITRDNodeConsoleServer(s *grpc.Server, srv ITRDNodeConsoleServer) {
	s.RegisterService(&_ITRDNodeConsole_serviceDesc, srv)
}

func _ITRDNodeConsole_Py2JobServerConsole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITRDNodeConsoleServer).Py2JobServerConsole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ITRDNodeConsole/Py2JobServerConsole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITRDNodeConsoleServer).Py2JobServerConsole(ctx, req.(*PyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ITRDNodeConsole_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.ITRDNodeConsole",
	HandlerType: (*ITRDNodeConsoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Py2JobServerConsole",
			Handler:    _ITRDNodeConsole_Py2JobServerConsole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "JobServerConsole.proto",
}
